### ISSUE TITLE
[Feature Request] Dateien in MS-Formaten

### ISSUE THREAD

**Issue by JaBecker** [tweh/lehrerwerkzeuge#4]
Es wäre hilfreich, die Dateien auch im docx- bzw. xslx-Format vorliegen zu haben, dann können diese auch mit Microsoft Office oder LibreOffice geöffnet werden. In Numbers bzw. Pages sollte das über das Export-Menü gehen.

**Comment by tweh** [comment]
Das wäre sicher hilfreich, ist aber in den meisten Fällen nicht (ohne Weiteres) möglich, weil Excel nur eine einzige Tabelle pro Blatt erlaubt, während ich an ganz vielen Stellen mehrere Tabellen pro Blatt nutze. 
Ich habe den automatischen Export mal für `sek1_arbeit` getestet. Dabei wird für jede Tabelle ein eigenes Blatt angelegt, was extrem unübersichtlich ist und es konnten laut Fehlermeldung auch nicht alle Formeln übernommen werden (Details dazu zeigt die Meldung nicht und ich habe gerade auch keine zeit, zu suchen, was nicht übernommen wurde). Die unveränderte XLSX-Datei kann man sich hier ansehen: https://www.file-upload.net/download-13715039/sek1_arbeit.xlsx.html. Dabei wird schnell klar, das, um Excel-Versionen wirklich sinnvoll nutzen zu können, eine manuelle Übertragung nötig wäre, die für mich (als Apple- und Numbers-User) aber keinen Mehrwert hat, weswegen ich das leider auch nicht anbieten kann …
