### ISSUE TITLE
Notentendenzen (+/-) bei Klassenarbeiten/ Klausuren

### ISSUE THREAD

**Issue by kliets** [tweh/lehrerwerkzeuge#75]
Ich gehe davon aus, es hat einen tieferen Grund, warum man bei den Klassenarbeiten (z.B. Sek 1) nur ganzzahlige Noten eingeben kann. Welcher ist das? Es wundert mich weil das doch eigentlich absolut üblich ist mit den Notentendenzen (+ und -) zu rechnen für die Gesamtnote. Ich wünschte mir das Feature sehr, da ich alle Ihre Tools super finde. Vielen Dank ! Meinen Sie, das wäre schnell machbar, die Tendenzen für die schriftlichen Arbeiten mit zu berücksichtigen? VG

**Comment by tweh** [comment]
Also da es in NDS (meinem BL) vorgeschrieben ist, dass bei schriftlichen Leistungen immer mit glatten Noten gerechnet wird, habe ich das auch nicht implementiert.

Es ist auch nicht unbedingt so leicht umzusetzen / zu definieren, weil man ja üblicherweise nur Punktegrenzen für ganzzahlige Noten angibt. Folgende Möglichkeiten fielen mir spontan ein.

1. Auch in der Sek 1 die Sek-2-Tabelle nutzen und die Punkte entsprechend umwandeln (15 → 1+, 14 → 1, …). Das könnte man direkt so nutzen, wenn man anstelle der Punkte (15, 14, …) in der Parametertabelle *Punktegrenzen* die Punkte Ziffern durch Noten (1+, 1, 1–, …) ersetzt. Dann müsste man halt entsprechende BE-Grenzen definieren. Das hätte den Nachteil, dass kein Durchschnitt mehr gebildet werden könnte, weil mit den Tendenznoten nicht gerechnet werden kann (außer man nutzt wieder nur Zahlen (0,7; 1,0; 1,3; …).
2. In der Sek-1-Version kann man die „knapp daneben“-Funktion dafür nutzen und entsprechend größere Grenzen dafür angeben. Dann müsste man den Mechanismus, der den Text in der Spalte „Hinweis“ ausgibt noch so umbauen, dass er nicht „knapp erreicht“ ausgibt sondern z.B. `AG4&"+"` oder `AG4-0,3`, um an die glatte Note die Tendenz anzufügen. Dabei würde zumindest die Zählung der glatten Noten für Durchschnitt und Diagramme etc. erhalten bleiben, man könnte aber zum Weiterrechnen dann aus der „Hinweis“-Spalte die Tendenznoten kopieren. Die Endnotentabellen sollten das ohnehin unterstützen auch mit Dezimalzahlen zu rechnen.
3. In der Sek-1-Version kann man natürlich auch direkt in der Notenspalte implementieren, dass eine Tendenz angeben wird, wenn die Prozentzahl innerhalb bestimmter Grenzen liegt. Das wäre aber recht aufwändig, weil dann auch die ganze Auswertung angepasst werden muss.

Ich werde in meinen Vorlagen aber aus dem genannten Grund nichts davon implementieren, weil ich diese Tabellen nicht selber nutzen würde und es dann immer doppelt Pflegen müsste. Aber Sie können natürlich ausgehend von den beschriebenen Ansätzen gern einen Fork von diesem Repository machen und es selbst anpassen.

Ich lasse diesen Isst trotzdem Vorerst offen, dann kann ich in den nächsten Sommerferien nochmal darüber nachdenken, ob ich es aufnehme oder nicht.

PS: Gern auch Kollegiales „du“ ;-)

**Comment by kliets** [comment]
Hallo Tobias, danke für die guten Hinweise. Ich habe das jetzt einmal versucht so anzupassen, dass es für Schleswig-Holstein (mit Tendenznoten) passt und bin einigermaßen zufrieden. Falls du Interesse hast, hier das [Ergebnis](https://github.com/kliets/Notentool-iPad-Sek1.git). Da es auf Grundlage deiner Arbeit entstand, habe ich dich dort erwähnt. Ich hoffe, das ist so in Ordnung für dich. VG

**Comment by tweh** [comment]
Guten Morgen, das sieht gut aus! Wenn du magst, verlinke ich das auch gern in meiner ReadMe, für die anderen SHler*innen.
